name: ess
description: Employee Management System for Premier Groups
publish_to: "none"
version: 39.0.0

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Stable and compatible versions for Flutter 3.22.0
  connectivity: ^3.0.6
  freezed_annotation: ^2.4.1
  fluttertoast: ^8.2.4
  confetti: ^0.7.0
  flutter_image_compress: ^2.1.0
  stacked: ^3.4.2
  stacked_services: ^1.3.0
  stacked_core: ^1.2.1
  stacked_generator: ^1.3.2
  autocomplete_textfield: ^2.0.0
  flutter_background_service: ^5.0.4
  flutter_typeahead: ^4.8.0
  flutter_svg: ^2.0.10+1
  flutter_html: ^3.0.0-beta.2
  local_auth: ^2.1.7
#  charts_flutter:
  flutter_advanced_drawer: ^1.3.4
  package_info: ^2.0.2
  dio: ^5.4.1
  url_launcher: ^6.2.6
  flutter_phone_direct_caller: ^2.1.0
  flutter_keyboard_visibility: ^5.4.1
  get: ^4.6.7
  shared_preferences: ^2.2.2
  flutter_slidable: ^3.0.0
  fl_chart: ^0.66.1
  sqflite: ^2.3.2
#  syncfusion_flutter_charts: ^24.1.41
  pie_chart: ^5.3.2
  file_selector: ^1.0.0
  image_picker: ^1.1.1
  hexcolor: ^3.0.1
  google_fonts: ^6.1.0
  cherry_toast:
#  slide_digital_clock:
  horizontal_data_table: ^4.1.4
  geolocator: ^10.1.0
  geocoding: ^2.2.0
  google_maps_flutter: ^2.6.0
  cloud_firestore: ^4.15.8
  firebase_core: ^2.27.0

  image: ^4.1.7
  firebase_messaging: ^14.7.21
  flutter_local_notifications: ^17.1.2
  permission_handler: ^11.3.1
  in_app_update: ^4.2.1
  lottie: ^3.1.0
  flutter_multi_formatter: ^2.12.6
  webview_flutter:
  flutter_spinkit: ^5.2.0
  http: ^1.0.0
  provider: ^6.1.2

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.4.5
  flutter_launcher_icons: ^0.13.1


dependency_overrides:
#  charts_flutter:
#    git:
#      url: https://github.com/google/charts.git
#      path: charts_flutter


flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  background_color: "#ffffff"
  adaptive_icon_background: "#ffffff"
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
















#name: ess
#description: emplyee management systems for premier groups
#
#publish_to: "none"
#
#
#version: 37.0.0
#environment:
#  sdk: ">=2.16.0 <4.0.0"
#
#dependencies:
#  flutter:
#    sdk: flutter
#  connectivity: ^3.0.6
#  freezed_annotation: ^2.2.0
#  fluttertoast:
#  confetti:
#  flutter_image_compress:
#  stacked: ^3.4.0
#  autocomplete_textfield: ^2.0.0
#  flutter_background_service: ^0.1.5
#  flutter_typeahead:
#  flutter_svg:
#  flutter_html:
#  stacked_services: ^1.1.0
#  local_auth:
#  flutter_advanced_drawer:
#  package_info: ^2.0.2
#  stacked_core:
#  dio: ^4.0.0
#  charts_flutter: ^0.12.0
#  url_launcher:
#  flutter_phone_direct_caller: ^2.0.2
#  flutter_keyboard_visibility: ^5.0.3
#  flutter_lints: ^2.0.0
#  get: ^4.6.6
#  shared_preferences: ^2.0.8
#  flutter_slidable: ^2.0.0
#  fl_chart: ^0.55.2
#  sqflite:
#  syncfusion_flutter_charts: ^20.4.42
#  pie_chart: ^5.3.2
#  image_picker: ^0.8.6
#  hexcolor: ^3.0.1
#  google_fonts: ^4.0.4
#  cherry_toast: ^1.11.0
#  slide_digital_clock: ^1.0.3
#  horizontal_data_table: ^4.1.4
#  geolocator: ^9.0.2
#  geocoding: ^2.0.5
#  google_maps_flutter: ^2.1.1
#  cloud_firestore: ^4.5.0
#  firebase_core: ^2.4.1
#  file_picker:
#  image:
#  firebase_messaging:
#  flutter_local_notifications: ^18.0.1
#  permission_handler:
#  in_app_update: ^4.0.1
#  lottie: ^2.2.0
#  flutter_multi_formatter: ^2.10.2
#  webview_flutter: ^2.0.0
#  flutter_spinkit:
#  http:
#  provider:
#
#dev_dependencies:
#  build_runner: ^2.3.3
#  stacked_generator: ^1.6.1
#  freezed: ^2.3.2
#  flutter_launcher_icons: ^0.11.0
#
#flutter_icons:
#  android: true
#  ios: true
#  remove_alpha_ios: true
#  background_color: "#ffffff"
#  adaptive_icon_background: "#ffffff"
#  image_path: "assets/images/logo.png"
#  min_sdk_android: 21
#
#flutter:
#  uses-material-design: true
#  assets:
#    - assets/images/